version: "3.8"
services:
  api1:
    build: .
    hostname: api1
    expose:
      - "8000"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.5GB'
    depends_on:
      - db
  api2:
    build: .
    hostname: api2
    expose:
      - "8000"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.5GB'
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '1.5GB'

volumes:
  postgres_data: 