version: "3.8"
services:
  api1:
    build: .
    hostname: api1
    # ports:
    #   - "8000:8000"
    expose:
      - 8000
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'
    depends_on:
      - db
  api2:
    build: .
    hostname: api2
    # ports:
    #   - "8001:8000"
    expose:
      - 8000
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'

  db:
    image: postgres
    hostname: db
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '1.5GB'

volumes:
  postgres_data: 